"""empty message

Revision ID: 0978f4181775
Revises: 5f15df0cd37d
Create Date: 2020-05-13 04:14:05.249335

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0978f4181775'
down_revision = '5f15df0cd37d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wcodes',
    sa.Column('index', sa.Integer(), nullable=False),
    sa.Column('no', sa.Integer(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('bonus_index', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['bonus_index'], ['numbers.index'], ),
    sa.PrimaryKeyConstraint('index'),
    sa.UniqueConstraint('no')
    )
    op.create_table('number_identifier',
    sa.Column('number_index', sa.Integer(), nullable=True),
    sa.Column('wcode_index', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['number_index'], ['numbers.index'], ),
    sa.ForeignKeyConstraint(['wcode_index'], ['wcodes.index'], )
    )
    op.drop_table('stars')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stars',
    sa.Column('index', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('value', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('index', name='stars_pkey'),
    sa.UniqueConstraint('value', name='stars_value_key')
    )
    op.drop_table('number_identifier')
    op.drop_table('wcodes')
    # ### end Alembic commands ###
