"""empty message

Revision ID: 17f39f6eaec3
Revises: 0978f4181775
Create Date: 2020-05-13 04:20:43.021404

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17f39f6eaec3'
down_revision = '0978f4181775'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lowcodes',
    sa.Column('index', sa.Integer(), nullable=False),
    sa.Column('no', sa.Integer(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('one', sa.Integer(), nullable=True),
    sa.Column('two', sa.Integer(), nullable=True),
    sa.Column('three', sa.Integer(), nullable=True),
    sa.Column('four', sa.Integer(), nullable=True),
    sa.Column('five', sa.Integer(), nullable=True),
    sa.Column('six', sa.Integer(), nullable=True),
    sa.Column('bonus', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('index'),
    sa.UniqueConstraint('no')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lowcodes')
    # ### end Alembic commands ###
